name: Relay Schema bot

on: [push]
jobs:
  call-workflow-passing-data:
    uses: Jay-flow/relay-schema-bot@master
    with:
      token: ${{ secrets.PAT }}
      repo-url: https://github.com/Jay-flow/artifacts-pro

      app-id: ${{ secrets.APP_ID }}
      app-private-key: ${{ secrets.APP_PRIVATE_KEY }}
